### ISSUE TITLE
Please update to 1.20.1

### ISSUE THREAD

**Issue by EGOIST1372** [MrBoogyBam/Chat-Coords#10]
Great mod
Thanks in advance <3

**Comment by Sylvorus** [comment]
bump (i think thats how it works)

**Comment by MrBoogyBam** [comment]
I didn't miss this, I just can't work on the mod right now, I'll port to 1.20.1 in a couple of days since I can't right now

**Comment by pizzav-xyz** [comment]
> 
@MrBoogyBam 
is it done?


> I didn't miss this, I just can't work on the mod right now, I'll port to 1.20.1 in a couple of days since I can't right now

**Comment by MrBoogyBam** [comment]
Finally done, newest version works with 1.20 and 1.20.1
