### ISSUE TITLE
[Feature request] Show dimension

### ISSUE THREAD

**Issue by griffin4cats** [MrBoogyBam/Chat-Coords#2]
When I send coordinates it would be helpful if it said the dimension as well. I can't imagine it'd be too hard to set up?

**Comment by MrBoogyBam** [comment]
i just did it you can install the latest version

**Comment by griffin4cats** [comment]
I installed the latest version, it does not work. All that changed is that it says x y or z before each respective number.

**Comment by MrBoogyBam** [comment]
oh i guess it didn't save, i'll fix it and just replace the download link file and let you know when its fixed

**Comment by MrBoogyBam** [comment]
ok should be fixed, you can download from the same release i just replaced the file
