### ISSUE TITLE
Various Messages Plugin Support

### ISSUE THREAD

**Issue by MadDog443** [MrBoogyBam/Chat-Coords#3]
Sometimes you don't want to drop coords in a public chat, do you think you could add in the config menu a text bar that allows us to place a prefixed command to either message it to someone specific or a specific group chat in game? 
Or a hotkey to copy it to your clipboard?
Or even a way to change or add multiple hotkeys with different prefixes?

**Comment by MrBoogyBam** [comment]
Lemme play you a sad song on the world's smallest violin

**Comment by MadDog443** [comment]
No need to be an asshole, could just say no. I don't even use this mod anymore, I made a script with JS Macros which is much better.

**Comment by MrBoogyBam** [comment]
The mod is meant for multiplayer with your friends. If you want to remember the coords just press f3 and take a screenshot. I was just making a hilarious spongebob reference

**Comment by MadDog443** [comment]
Actually, the reason I suggested it was because if you're getting attacked by another player you might not want to broadcast your coords to whole world. Messaging a player or sending it in another chat group on the server would be a better option.
