### ISSUE TITLE
Plugin produces "This line is printed by an example mixin" log messages

### ISSUE THREAD

**Issue by MichailiK** [MrBoogyBam/Chat-Coords#4]
Every time the title screen is displayed, the following log message gets printed:

`[Render thread/INFO]: This line is printed by an example mod mixin!`

This is caused by the example mixin being unintentionally left in.

https://github.com/MrBoogyBam/Chat-Coords/blob/582917a5cc7ff7b229b7672b75c81f90cf8b0727/src/main/java/net/mrboogybam/chatcoords/mixin/ChatCoordsMixin.java#L12-L15

I am slightly bothered by it, please remove the mixin.

**Comment by BarackOBusiness** [comment]
Should be fixed now once the latest artifact builds, will be pushed to modrinth soon
