### ISSUE TITLE
Crash on 1.19.3

### ISSUE THREAD

**Issue by voidrinix** [MrBoogyBam/Chat-Coords#7]
Hi! I pressed the assigned keybind and minecraft crashed. Here is the log 
[crash-2022-12-29_22.17.19-client.txt](https://github.com/MrBoogyBam/Chat-Coords/files/10321213/crash-2022-12-29_22.17.19-client.txt)

**Comment by MrBoogyBam** [comment]
Mod should be fixed on 1.19.3 now
